print('01\twrite python program to enter length and breadth of a rectangle and calculate and perimeter of the rectangle')
l=input('enter the length of the rectangle')
b=input('enter the breadth of the rectangle')
print('the area of the rectangle is '+ str(float(l*b))+' sq. units')
print('the perimeter of the rectangle is '+ str(float((2*l)+(2*b)))+' units')
